### ISSUE TITLE
not working on windows 8.1

### ISSUE THREAD

**Issue by Kingkohla** [brianch/offline-chess-puzzles#1]
offline-chess-puzzles.exe doesn't run

**Comment by brianch** [comment]
Hello,

do you get any error message? Is your Windows 32 or 64 bit ? 

The executable was created in windows 10 and tested there, I used the x86_64-pc-windows-msvc target when compiling and that's what might be causing the problem on Windows 8.1, perhaps using the GNU toolchain would be better, although I had a problem when I tried it the first time.

I'll look into it, thanks for reporting.

**Comment by Shine0717** [comment]
First of all, thank you very much for your work. I have searched for similar software for a long time, but only this program you made is the best!

I use this program almost every day since I found it last month, because I often work in an environment without network. This program solved the needs of some of us.

I can only use it under win10. But it cannot be used under win7. (There is no any system message, a window similar with DOS flashed, and then disappeared.)

I am willing donate to express my gratitude!

My email is peter.lee.acct@gmail.com, hope to get your reply.

**Comment by brianch** [comment]
I'm so happy that it's been useful for you @Shine0717 ! Thanks a lot for your words :)

I was investigating this and it doesn't appear to be the library issue I was imagining before, can one of you open the app in a cmd window to see if there's any messages?

You can open a file explorer, go to the directory where the exe is, click on the address bar and type "cmd", it should open a command prompt in that directory, in the cmd window you type the full name of the .exe (you can auto-complete with tab), an error message may be visible that way.

Please also try the executable in the zip below (you can unzip in the same directory as the non-working exe), it uses a different way to render the interface, it is uglier (it's using a font for the pieces instead of images) but is more compatible and may work (or may not, I'm really not sure).

I don't actually use Windows and that's why it's a bit hard for me to test these things, I'm creating these Windows files in a Virtual Machines but it's painfully slow.

[test-glow.zip](https://github.com/brianch/offline-chess-puzzles/files/6984150/test-glow.zip)

**Comment by Shine0717** [comment]
@brianch You are amazing. You haven't received for my feedback, but you have already made a solution files.

After I strictly followed your instructions, this is displayed in the CMD window:
![image](https://user-images.githubusercontent.com/88195849/130008967-14b6225a-46f1-46da-9844-6df23dc6ef71.png)

----------------------------------------------------
D:\>offline-chess-puzzles.exe
Error: GraphicsAdapterNotFound

D:\>_
----------------------------------------------------
After using your updated file, it worked in Win7. Indeed, it's a little bit 'uglier', but I'll get to used it. ^_^  If in that case, I perfer to use win10, so that I can customize my  pieces style.
![image](https://user-images.githubusercontent.com/88195849/130009004-20a47084-2aed-4ade-9d19-35f4d66e9fba.png)


I'm looking forward to your new features, such as Highlight the last move, Moved & clicked sound, etc.

**Comment by brianch** [comment]
Thanks a lot for testing!

Yeah, this is what I was suspecting, the library I'm using to render the interface requires dx12 or Vulkan, and that's why you get the GraphicsAdapterNotFound error.

The other way (used in the test-glow.zip) should work everywhere but images aren't supported yet (but they could in the future, that would make things way easier). I think I'll ship both .exe files in the next release.

Thanks again :)

**Comment by brianch** [comment]
In the 1.1 release I put both versions of the app, you can use the "offline-chess-puzzles-win7.exe" for Windows versions older than 10. When images get supported in the glow renderer of the iced library we will be able to switch to a single .exe that looks good and works everywhere.

I'll close this now.
