### ISSUE TITLE
vcruntime140.dll needed in win7 and on win10 the labels sometimes are not shown correctly

### ISSUE THREAD

**Issue by Shine0717** [brianch/offline-chess-puzzles#3]
Congratulations Brianch has released the new version!

Since the last version was released, I have checked it out almost every day. Whenever I see the "code" page, it shows modified "a few hours, or days", I am very excited. Thank you very much for your hard work, Brianch.

After version of 2.0, I've been a little busy at work this month, so I didn't play it very often.

I tried it on the win7, and it noticed me that a 'VCRUNTIME140.dll' file is missing. I guess its my computer's problem.

But when I tried it on win10 system, sometimes there are strange "patterns" on the screen. I don't know if this is my computer's problem. Anyway it's not a big problem, you don't need to fix it in hurry.
![strange](https://user-images.githubusercontent.com/88195849/138212919-99f4fdc6-0c25-44b1-8fd1-079438a96237.png)

**Comment by Shine0717** [comment]
Hi Brianch,

1. Recently it was working alright, I guess it was my computer's problem.
2. I set the value 90 (under 1920*1080)
3. Since the new vision cannot run in Win7(VCRUNTIME140.dll error), I haven't test it yet.
4. I have just updated my GPU driver, but it still happen.

I don't think you need to fix anything, we'll get to used it.

**Comment by brianch** [comment]
Hi!

So the visual glitch isn't happening anymore at all? I'm a bit confused with the answers for the 1st and 4th questions, because in the 4th one you said it still happens.

In the current code, the promotion piece images should be ok now with a 90 square size (after commit 344386855625ca1afa380870a7f9aa0e0efce244) but I guess I could increase it horizontally even more actually.

And yes, I understood that it isn't running in windows 7, I was asking if the "offline-chess-puzzles-w7-64bits.exe" works well in Windows 10 instead. By the way, you can't install that Microsoft library in the windows 7 computer?

In the future I should use a CI/CD tool to build the Windows binaries, I don't even have the Windows virtual machine to do it anymore because I was running out of hard drive space.

**Comment by Shine0717** [comment]
Hi, Brianch.

I've just tested the win7 version, after following your instruction that downloaded the library from Microsoft's website, it's working alright.

And there's no any visual glitch occurred(window size:75, under 1366x768).

I suggest please don't close this "issue", because the download link that you provided is very useful. Some users who occur this problem may need this.

When I go back to my win10 computer, I'll try it again, and let you know whether the visual glitch problem still occur after I use a new GPU(RTX 2060).

**Comment by brianch** [comment]
Since there was no further report about the labels issue, and the vcruntime thing should be fixed now after the last few changes on the github actions workflow, I'm gonna close this.
