### ISSUE TITLE
crash under windows10

### ISSUE THREAD

**Issue by skydig** [brianch/offline-chess-puzzles#4]
warning: field is never read: `puzzle_db_location`
  --> src\settings.rs:34:5
   |
34 |     puzzle_db_location: text_input::State,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: `offline-chess-puzzles` (bin "offline-chess-puzzles") generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 3m 42s
     Running `target\debug\offline-chess-puzzles.exe`
error: process didn't exit successfully: `target\debug\offline-chess-puzzles.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)

**Comment by brianch** [comment]
Hello,

Which branch are you compiling? I found it strange that I don't receive this warning so I wonder if you're trying to compile an old version.

And since you're on Windows, take a look at the Cargo.toml and switch the soloud line like I said in the comments if you haven't done so already.

It probably doesn't make a difference but I'm running rust stable here.

**Comment by skydig** [comment]
@brianch 
thanks, I switch the soloud line, it's ok now.
